# Generated by Django 5.0.6 on 2024-05-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok_miktari', models.PositiveIntegerField()),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('kilo', 'Kilo')], max_length=50)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter.kategori')),
            ],
        ),
    ]
