# Generated by Django 5.0.6 on 2024-05-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='fotoğraf',
            field=models.ImageField(blank=True, null=True, upload_to='urun_fotograflari/'),
        ),
    ]
