# Generated by Django 5.0.6 on 2024-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0004_auto_20240531_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
