# Generated by Django 5.0.6 on 2024-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0005_alter_urun_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
