# Generated by Django 5.0.6 on 2024-05-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0006_kategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='para_birimi',
            field=models.CharField(choices=[('TL', 'Türk Lirası'), ('USD', 'Dolar'), ('EUR', 'Euro')], default='TL', max_length=3),
        ),
    ]
