# Generated by Django 5.0.6 on 2024-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0007_urun_para_birimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='eski_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
