# Generated by Django 5.0.6 on 2024-05-31 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0008_urun_eski_fiyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='kategori',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='envanter.kategori'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='isim',
            field=models.CharField(max_length=100),
        ),
    ]
