# Generated by Django 5.0.6 on 2024-06-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0009_remove_kategori_aciklama_kategori_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RemoveField(
            model_name='urun',
            name='fotoğraf',
        ),
        migrations.CreateModel(
            name='UrunFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='urun_fotograflari/')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotolar', to='envanter.urun')),
            ],
        ),
    ]
