# Generated by Django 3.2.7 on 2024-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0010_alter_kategori_options_alter_urun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='fotoğraf',
            field=models.ImageField(blank=True, null=True, upload_to='urun_fotograflari/'),
        ),
    ]
